
import csv.Extractor;
import models.entities.Entity;
import models.entities.fictional.*;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;

public class CsvWriterRunner {
    @Test
    public void runWriteCsv() throws Exception {
        User user = new User();
        user.id = 1;
        user.name = "Ddff";
        user.age = 24;
        user.autos = new ArrayList<>();
            Auto ferrari = new Auto();
            ferrari.id = 3;
            ferrari.model = "Ferrari";
            ferrari.color = "red";
            ferrari.userId = 1;
            ferrari.sellers = new ArrayList<>();
                Seller seller1 = new Seller();
                seller1.id = 12;
                seller1.name = "SellerOne";
                seller1.autoId = 3;
                Seller seller2 = new Seller();
                seller2.id = 14;
                seller2.name = "SellerTwo";
                seller2.autoId = 3;
            ferrari.sellers.add(seller1);
            ferrari.sellers.add(seller2);
            ferrari.owners = new ArrayList<>();
                Owner owner1 = new Owner();
                owner1.id = 23;
                owner1.name = "Aaaaa";
                owner1.autoId = 3;
                Owner owner2 = new Owner();
                owner2.id = 24;
                owner2.name = "Sssss";
                owner2.autoId = 3;
            ferrari.owners.add(owner1);
            ferrari.owners.add(owner2);
        user.autos.add(ferrari);
            Auto ford = new Auto();
            ford.id = 2;
            ford.model = "Ford";
            ford.color = "black";
            ford.userId = 1;
            ford.sellers = new ArrayList<>();
            Seller seller3 = new Seller();
                seller3.id = 15;
                seller3.name = "SellerThree";
                seller3.autoId = 2;
                Seller seller4= new Seller();
                seller4.id = 16;
                seller4.name = "SellerFour";
                seller4.autoId = 2;
            ford.sellers.add(seller3);
            ford.sellers.add(seller4);
            ford.owners = new ArrayList<>();
            Owner owner3 = new Owner();
            owner3.id = 25;
            owner3.name = "Ddddd";
            owner3.autoId = 2;
            Owner owner4 = new Owner();
            owner4.id = 26;
            owner4.name = "Fffff";
            owner4.autoId = 2;
            ford.owners.add(owner3);
            ford.owners.add(owner4);
        user.autos.add(ford);


        User user1 = new User();
        user1.id = 11;
        user1.name = "1Ddff";
        user1.age = 124;
        user1.autos = new ArrayList<>();
            Auto ferrari1 = new Auto();
            ferrari1.id = 13;
            ferrari1.model = "1Ferrari";
            ferrari1.color = "1red";
            ferrari1.userId = 11;
            ferrari1.sellers = new ArrayList<>();
                Seller seller11 = new Seller();
                seller11.id = 112;
                seller11.name = "1SellerOne";
                seller11.autoId = 13;
                Seller seller21 = new Seller();
                seller21.id = 114;
                seller21.name = "1SellerTwo";
                seller21.autoId = 13;
        ferrari1.sellers.add(seller11);
        ferrari1.sellers.add(seller21);
        ferrari1.owners = new ArrayList<>();
        Owner owner11 = new Owner();
        owner11.id = 123;
        owner11.name = "1Aaaaa";
        owner11.autoId = 13;
        Owner owner21 = new Owner();
        owner21.id = 124;
        owner21.name = "1Sssss";
        owner21.autoId = 13;
        ferrari1.owners.add(owner1);
        ferrari1.owners.add(owner2);
        user1.autos.add(ferrari1);
        Auto ford1 = new Auto();
        ford1.id = 12;
        ford1.model = "1Ford";
        ford1.color = "1black";
        ford1.userId = 11;
        ford1.sellers = new ArrayList<>();
        Seller seller31 = new Seller();
        seller31.id = 115;
        seller31.name = "1SellerThree";
        seller31.autoId = 12;
        Seller seller41= new Seller();
        seller41.id = 116;
        seller41.name = "1SellerFour";
        seller41.autoId = 12;
        ford1.sellers.add(seller11);
        ford1.sellers.add(seller21);
        ford1.owners = new ArrayList<>();
        Owner owner31 = new Owner();
        owner31.id = 125;
        owner31.name = "1Ddddd";
        owner31.autoId = 12;
        Owner owner41 = new Owner();
        owner41.id = 126;
        owner41.name = "1Fffff";
        owner41.autoId = 12;
        ford1.owners.add(owner2);
        ford1.owners.add(owner3);
        user1.autos.add(ford1);

        ArrayList<Entity> users = new ArrayList<>();
        users.add(user);
        users.add(user1);

        new Extractor().writeEntitiesToCsv(users);
    }
}
